before_install:
  - gem install bundler

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - 2.7.0
  - ruby-head
  - rbx
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-6.0.x
  - gemfiles/Gemfile.rails-master

matrix:
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: jruby
      gemfile: gemfiles/Gemfile.rails-master
  allow_failures:
    - rvm: rbx
  fast_finish: true
